export enum PurposeTokenName {
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    PASSWORD_RESET = 'PASSWORD_RESET',
    INVITATION = 'INVITATION',
    CHANGE_EMAIL = 'CHANGE_EMAIL',
    ACCOUNT_UNLOCK = 'ACCOUNT_UNLOCK' 
}